Project module initialization
alibabacloud-automation/terraform-alicloud-service-mesh pull request #1
Opened 2022-03-23 02:09 UTC by susu9527

2022-03-23 11:37 UTC, xiaozhu36 requested changes

2022-03-23 11:37 UTC, xiaozhu36 commented on main.tf
> +    vswitche_list = [alicloud_vswitch.example.id]
这个地方不要把所有子参数都暴露为一个单独的参数，对外应该只暴露一个参数 network，然后这个参数是一个 map，这个参数中可以设置两个参数 vpc_id 和 vswitche_list
其他的参数也一样

2022-03-23 11:37 UTC, xiaozhu36 commented on main.tf
> +resource "alicloud_service_mesh_service_mesh" "example" {
不要用 example 这种没有意义的标识，可以用 alicloud_service_mesh_service_mesh 的缩写或者后缀 mesh

2022-03-23 11:37 UTC, xiaozhu36 commented on main.tf
> +resource "alicloud_vswitch" "example" {
main 中不要有其他的资源，只包含 service mesh 的资源即可

2022-03-23 11:37 UTC, xiaozhu36 commented on main.tf
> +    opa {
对于这种对外构造一个 mesh_config_opa 的参数，类型也是map即可

2022-03-23 11:37 UTC, xiaozhu36 commented on versions.tf
> +  required_providers {
去掉required_providers

2022-03-23 11:37 UTC, xiaozhu36 commented on variables.tf
> +  default     = null
对于这种bool类型的，默认值设置为 false 就好

2022-03-23 11:37 UTC, xiaozhu36 commented on variables.tf
> +  default     = null
对于这种有枚举值的参数，默认值设置为其中一个枚举值即可

2022-03-24 07:20 UTC, susu9527 commented on main.tf
> +    vswitche_list = [alicloud_vswitch.example.id]
vpc_id是string   vswitche_list是list（string），两个类型不同不能定义到map里

2022-03-24 07:57 UTC, xiaozhu36 requested changes

2022-03-24 07:57 UTC, xiaozhu36 commented on outputs.tf
> +output "this_service_mesh_status" {
去掉 this，就改为 service_mesh_id 和 service_mesh_status

2022-03-24 07:57 UTC, xiaozhu36 commented on variables.tf
> +variable "vswitche_list" {
这个改成 vswitch_ids

2022-03-24 07:57 UTC, xiaozhu36 commented on variables.tf
> +  default     = {}
还是把这些前缀 mesh_config 去掉吧，就叫做 access_log
其他的也一样

2022-03-24 08:30 UTC, xiaozhu36 requested changes

2022-03-24 08:30 UTC, xiaozhu36 commented on main.tf
> +  service_mesh_name = var.name
每个资源需要一个控制开关来控制一个资源是否需要创建，可以参考下：https://github.com/terraform-alicloud-modules/terraform-alicloud-clickhouse/blob/main/main.tf#L2

2022-03-24 09:16 UTC, merged